# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09633a00c30375ac16e76b8ba2439e2470a89125e131b4177339b183d2ace2b597426dafd29df5ef250442a615246cf3d838d77fba44337d9b5feb0da95e7356

test:
  secret_key_base: b97091918daf28c8c09ae9b04a6a419feb77b5fd43519e76c7d8615509c5fbf8e0f8c30aa68f4a9d01c4d53000a50bae1102686619878c681679a90736ac377e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
